TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/AuthorsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class AuthorsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/CommentsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class CommentsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/PostsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TatBlog.Core.Entities;
using TatBlog.Services.Blogs;
using TatBlog.WebApp.Areas.Admin.Models;
using MapsterMapper;
using TatBlog.Services.Media;
using FluentValidation;
using FluentValidation.AspNetCore;
using Microsoft.AspNetCore.Identity;
using TatBlog.WebApp.Validations;
using TatBlog.Core.Contracts;


namespace TatBlog.WebApp.Areas.Admin.Controllers
{

    public class PostsController : Controller
    {
        private readonly ILogger<PostsController> _logger;
        private readonly IBlogRepository _blogRepository;
        private readonly IMediaManager _mediaManager;
        private readonly IMapper _mapper;
        

        public PostsController(IBlogRepository blogRepository,
            ILogger<PostsController> logger , 
            IMapper mapper, 
            IMediaManager mediaManager )
        {
            _blogRepository = blogRepository;
            _mapper = mapper;
            _logger = logger;
            _mediaManager = mediaManager;
            
            
        }
        
        private async Task PopulatePostFilterModelAsync(PostFilterModel model)
        {
            var authors = await _blogRepository.GetAuthorsAsync();
            var categories = await _blogRepository.GetCategoryItemsAsync();

            model.AuthorList = authors.Select(a => new SelectListItem()
            {
                Text = a.FullName,
                Value = a.Id.ToString()
            });
            model.CategoryList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
        }

       private async Task PopulatePostEditModelAsync(PostEditModel model)
        {
            var authors = await _blogRepository.GetAuthorsAsync();
            var categories = await _blogRepository.GetCategoryItemsAsync();

            model.AuthorList = authors.Select(a => new SelectListItem()
            {
                Text = a.FullName,
                Value = a.Id.ToString()
            });
            model.CategoryList = categories.Select(c => new SelectListItem()
            {
                Text = c.Name,
                Value = c.Id.ToString()
            });
        }


        [HttpGet]
        public async Task<IActionResult>Index(PostFilterModel model)
        {
            var postQuery = _mapper.Map<PostQuery>(model);


            ViewBag.PostsList = await _blogRepository
                .GetPagedPostsAsync(postQuery, 1, 10);

            await PopulatePostFilterModelAsync(model);

            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id = 0)
        {
            var post = id > 0
                ? await _blogRepository.GetPostByIdAsync(id, true)
                : null;

            var model = post == null
                ? new PostEditModel()
                : _mapper.Map<PostEditModel>(post);

            await PopulatePostEditModelAsync(model);

            return View(model);
        }


        [HttpPost]
        
        public async Task<IActionResult> Edit(
            IValidator<PostEditModel> postValidator,
            PostEditModel model)  
            
        {
            
            var validationResult = await postValidator.ValidateAsync(model);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(ModelState);
            }

            if (!ModelState.IsValid)
            {
                await PopulatePostEditModelAsync(model);
                return View(model);
            }

            var post = model.Id > 0
                ? await _blogRepository.GetPostByIdAsync(model.Id)
                : null;

            if (post == null)
            {
                post = _mapper.Map<Post>(model);
                post.Id = 0;
                post.PostedDate = DateTime.Now;
            }
            else
            {
                _mapper.Map(model, post);

                post.Category = null;
                post.ModifiedDate = DateTime.Now;
            }

            if (model.ImageFile?.Length > 0)
            {
                var newImagePath = await _mediaManager.SaveFileAsync(
                    model.ImageFile.OpenReadStream(),
                    model.ImageFile.FileName,
                    model.ImageFile.ContentType);
                if (!string.IsNullOrWhiteSpace(newImagePath))
                {
                    await _mediaManager.DeleteFileAsync(post.ImageUrl);
                    post.ImageUrl = newImagePath;
                }
            }

            await _blogRepository.CreateOrUpdatePostAsync(post, model.GetSelectedTags());

            return RedirectToAction(nameof(Index));
        }

        [HttpPost]

        public async Task<IActionResult> VerifyPostSlug(int id, string urlSlug)
        {
            var slugExistedd = await _blogRepository
                .IsPostSlugExistedAsync(id, urlSlug);

            return slugExistedd
                ? Json($"Slug '{urlSlug}' đã được sửa dụng")
                : Json(true);
        }


    }
}

TipsAndTricks/TatBlog.WebApp/Areas/Admin/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;

namespace TatBlog.WebApp.Areas.Admin.Controllers
{
    public class TagsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>


<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale= 1.0" />
    <title>@ViewData["PageTitle"] - Tips & Tricks Blog</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />

    @await RenderSectionAsync("styles", required: false)
</head>
<body>
    <partial name="_NavBar" />
    <div class="container-fluid">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid text-center">
            &copy; 2023 - Tip & Tricks Blog
        </div>

    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/bootstrap.bundle.min.js"></script>
    <script src="~/js/main.js" asp-append-version="true"></script>

    @await RenderSectionAsync("scripts", required: false)
</body>
</html>

TipsAndTricks/TatBlog.WebApp/Areas/Admin/Views/Shared/_NavBar.cshtml
<header>
    <nav class="navbar navbar-expand-sm
                navbar-toggleable-sm navbar-light
                bg-white border-bottom box-shadow">
        <div class="container-fluid">
            <a class="navbar-brand"
               asp-area="Admin"
               asp-controller="Dashboard"
               asp-action="Index">
                Tip & Tricks
            </a>
            <button class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Categories"
                           asp-action="Index"
                           title="Xem danh sách chủ đề">
                            Chủ đề
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Authors"
                           asp-action="Index"
                           title="Xem danh sách tác giả">
                            Tác giả
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Tags"
                           asp-action="Index"
                           title="Xem danh sách thẻ/ từ khoá">
                            Thẻ
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Posts"
                           asp-action="Index"
                           title="Xem danh sách bài viết">
                            Bài viết
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark"
                           asp-area="Admin"
                           asp-controller="Comments"
                           asp-action="Index"
                           title="Xem danh sách bình luận">
                            Bình luận
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>