TipsAndTricks/TatBlog.WebApp/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using TatBlog.Services.Blogs;



namespace TatBlog.WebApp.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBlogRepository _blogRepository;

        public BlogController(IBlogRepository blogRepository)
        {
            _blogRepository = blogRepository;
        }

        public async Task<IActionResult> Index(
            [FromQuery(Name = "k")] string keyword = "",
            [FromQuery(Name = "p")] int pageNumber = 1,
            [FromQuery(Name = "ps")] int pageSize = 10)
        {
            var postQuery = new PostQuery()
            {
                PublishedOnly = true,

                Keyword = keyword
            };

            var postsList = await _blogRepository.GetPagedPostsAsync(postQuery, pageNumber, pageSize);

            ViewBag.PostQuery = postQuery;

            return View(postsList);
        }

        public IActionResult About()
            => View();
        public IActionResult Contact()
           => View();
        public IActionResult Rss()
           => Content("Nội dung sẽ được cập nhập");
    }
}

TipsAndTricks/TatBlog.WebApp/Views/Blog/About.cshtml
@{
    ViewData["PageTitle"] = "Giới thiệu";
}
<h1>
    Đây là trang giới thiệu
</h1>

TipsAndTricks/TatBlog.WebApp/Views/Blog/Contact.cshtml
@{
    ViewData["PageTitle"] = "Liên hệ";
}
<h1>
    Đây là trang liên hệ
</h1>

TipsAndTricks/TatBlog.WebApp/Views/Blog/Index.cshtml
@using TatBlog.Core.Entities;
@using TatBlog.Services.Blogs;
@using TatBlog.Core.Contracts;

@model IPagedList<Post>

@{
    ViewData["PageTitle"] = "Trang chủ";

    var postQuery = (ViewBag.PostQuery as PostQuery) ?? new PostQuery();
}

<div class="p-4">
    @if (!string.IsNullOrWhiteSpace(postQuery.Keyword))
    {
        <h3 class="text-primary mb-3">
            Những bài viết chứa từ khóa '@postQuery.Keyword'
        </h3>
    }

    @foreach (var postList in Model)
    {
        <partial name="_PostList" model="postList" />
    }
    <partial name="_Pager" model="@Model" />
</div>

<h1>
    Đây là trang chủ
</h1>

<p>
    Bây giờ là : @ViewBag.CurrentTime
</p>

TipsAndTricks/TatBlog.WebApp/Views/Blog/_Pager.cshtml
@using TatBlog.Core.Entities;
@using TatBlog.Services.Blogs;
@using TatBlog.Core.Contracts;

@model IPagedList<Post>

@{
    var postQuery = (ViewBag.PostQuery as PostQuery) ?? new PostQuery();
    var actionName = "Index";
    var slug = "";

    if (!string.IsNullOrWhiteSpace(postQuery.AuthorSlug))
    {
        actionName = "Author";
    }
    else if (!string.IsNullOrEmpty(postQuery.CategorySlug))
    {
        actionName = "Category";
    }

    else if (!string.IsNullOrEmpty(postQuery.TagSlug))
    {
        actionName = "Tag";
    }
}

@if (Model.PageCount > 1)
{
    <div class="text-center my-4">
        @if (Model.HasPreviousPage)
        {
            <a asp-controller="Blog"
               asp-action="@actionName"
               asp-route-slug="@slug"
               asp-route-k="@postQuery.Keyword"
               asp-route-p="@(Model.PageNumber - 1)"
               asp-route-ps="@Model.PageSize"
               class="btn btn-info">
                <i class="fa fa-arrow-left"></i>
                Trang trước
            </a>
        }
        else
        {
            <button type="button"
                    class="btn btn-outline-secondary"
                    disabled>
                <i class="fa fa-arrow-left"></i>
                Trang trước
            </button>
        }

        @if (Model.HasNextPage)
        {
            <a asp-controller="Blog"
               asp-action="@actionName"
               asp-route-slug="@slug"
               asp-route-k="@postQuery.Keyword"
               asp-route-p="@(Model.PageNumber + 1)"
               asp-route-ps="@Model.PageSize"
               class="btn btn-info">
                Trang sau
                <i class="fa fa-arrow-right"></i>
            </a>
        }
        else
        {
            <button type="button"
                    class="btn btn-outline-secondary"
                    disabled>
                Trang sau
                <i class="fa fa-arrow-right"></i>
            </button>
        }
    </div>
}

TipsAndTricks/TatBlog.WebApp/Views/Blog/_PostList.cshtml
@using TatBlog.Core.Entities;

@model Post

@{
    var imageUrl = string.IsNullOrWhiteSpace(Model.ImageUrl)
            ? "./images/image_1.jpg"
            : $"/{Model.ImageUrl}";
}
<article class="blog-entry mb-4">
    <div class="card">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@imageUrl"
                    class="card-img"
                    alt="@Model.Title" />
            </div>
            <div class="col-md-8">
                <div class="card-body">

                    <a class="card-title"
                        asp-controller="Blog" 
                        asp-action="Post" 
                        asp-route-year="@Model.PostedDate.Year"
                        asp-route-month="@Model.PostedDate.Month"
                        asp-route-day="@Model.PostedDate.Day"
                        asp-route-slug="@Model.UrlSlug" 
                        >
                        @Model.Title
                    </a>
                    <p class="card-text">
                        <small class="text-muted">
                            Tác giả:
                        </small>
                        <a asp-controller="Blog"
                           asp-action="Author"
                           asp-route-slug="@Model.Author"
                           class="text-primary">
                            @Model.Author
                        </a>

                        <small class="text-muted">
                            Chủ đề:
                        </small>
                        <a asp-controller="Blog"
                           asp-action="Category"
                           asp-route-slug="@Model.Category"
                           class="text-primary">
                            @Model.Category
                        </a>
                    </p>
                    <p class="card-text">
                        @Html.Raw(Model.ShortDescription)
                    </p>
                    @*<div class="tag-list">
                        <partial name="_TagList" model="@Model.Tags" />
                    </div>*@
                    <div class="text-end">
                        <a asp-controller="Blog"
                            asp-action="Post"
                            asp-route-year="@Model.PostedDate.Year"
                           asp-route-month="@Model.PostedDate.Month"
                           asp-route-day="@Model.PostedDate.Day"
                           asp-route-slug="@Model.UrlSlug"
                           class="btn btn-primary"
                           title="@Model.Title">
                           Xem chi tiết
                       </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>

TipsAndTricks/TatBlog.WebApp/Views/Blog/_TagList.cshtml
@using TatBlog.Core.Entities

@model IList<Tag>

@foreach (var item in Model)
{
    <a 
        asp-controller="Blog"
       asp-action="Tag"
       asp-route-slug="@item.UrlSlug"
       title="Tag: @item.Name"
       class="btn btn-sm btn-outline-secondary">
        @item.Name
    </a>
}